services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      target: ${APP_BUILD_TARGET:-deploy}
    #depends_on:
    #  mysql:
    #    condition: service_healthy
    env_file:
      - ./.env
    working_dir: /var/www/html
    volumes:
      - "./docker/app/php.ini-development:/usr/local/etc/php/php.ini"
      - ".:/var/www/html/"
    networks:
      - backend
    user: '82:82'
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      target: ${APP_BUILD_TARGET:-deploy}
    depends_on:
      - app
      - mysql
    volumes:
      - ".:/var/www/html"
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - ${NGINX_PORT:-9001}:80
    networks:
      - backend
  mysql:
    image: 'mysql/mysql-server:8.0'
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './docker/mysql/dumps:/docker-entrypoint-initdb.d'
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}" ]
      retries: 3
      timeout: 5s

  pma:
    image: linuxserver/phpmyadmin:latest
    links:
      - mysql
    environment:
      - PMA_ABSOLUTE_URI=/phpmyadmin/
      - PMA_HOST=mysql
      - PHP_INI_SESSION.gc_maxlifetime=3600
      - SESSION_TIMEOUT=86400
      - UPLOAD_LIMIT=100M
    depends_on:
      - mysql
    restart: always
    networks:
      - backend
    volumes:
      - session_data:/var/lib/php/sessions


networks:
  backend:
    external: false

volumes:
  session_data:
  sail-mysql:
